packages:
  - apps/*
  - packages/*
  - examples/*
  - templates/*
  - '!**/test/**'
minimumReleaseAge: 0
versioning:
  changelog:
    storage: repository
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  '@tailwindcss/oxide': true
  '@tarojs/binding': true
  '@tarojs/cli': true
  core-js: true
  core-js-pure: true
  esbuild: true
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
  workerd: true
