packages:
  - apps/*
  - packages/*
  - examples/*
  - templates/*
  - '!**/test/**'
minimumReleaseAge: 0
overrides:
  '@tarojs/cli>axios': 1.20.0
  hono: 4.13.7
versioning:
  changelog:
    storage: repository
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  '@tailwindcss/oxide': true
  '@tarojs/binding': true
  '@tarojs/cli': true
  core-js: true
  core-js-pure: true
  esbuild: true
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
  workerd: true
patchedDependencies:
  '@icebreakers/monorepo@5.6.0': patches/@icebreakers__monorepo@5.6.0.patch
